/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee;

import autozencarmanagmentsystem.*;
import java.math.BigDecimal;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
import com.toedter.calendar.JMonthChooser;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.SwingUtilities;
import java.awt.Component;
import java.awt.Color;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author malsh
 */
public class Otherexpences1 extends javax.swing.JFrame {

    /**
     * Creates new form CarManagement
     */
    public Otherexpences1() {
        initComponents();
        jButton6.setEnabled(false);
        billtableload();

    }

    public void billtableload() {  //number 1
        try {
            DefaultTableModel dt = (DefaultTableModel) otherbill_table.getModel(); //load table and store to dt
            dt.setRowCount(0);  // Clear existing rows before loading new ones

            Statement s = db.myccon().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM otherbills"); //execute quary

            while (rs.next()) {
                Vector v = new Vector();

                // Add each column value from the result set to the vector
                v.add(rs.getString("biiid"));
                v.add(rs.getString("category"));
                v.add(rs.getString("year"));
                v.add(rs.getString("month"));
                v.add(rs.getString("amount"));
                v.add(rs.getString("status"));

                // ✅ Add the vector as a row to the table model
                dt.addRow(v);
            }
            DefaultTableCellRenderer statusRenderer = new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int column) {

                    Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                    if (value != null) {
                        String status = value.toString().toLowerCase();

                        if (status.equals("paid")) {
                            c.setForeground(Color.BLACK);
                        } else if (status.equals("unpaid")) {
                            c.setForeground(Color.RED);
                        } else {
                            c.setForeground(Color.BLACK);
                        }
                    }

                    if (isSelected) {
                        c.setBackground(table.getSelectionBackground());
                    } else {
                        c.setBackground(Color.WHITE);
                    }

                    return c;
                }
            };

            otherbill_table.getColumnModel().getColumn(5).setCellRenderer(statusRenderer);

        } catch (Exception e) {
            e.printStackTrace();  // Print error to the console
            JOptionPane.showMessageDialog(null, "Error loading data into table: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        otherbill_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbillid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcategory = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtyear = new javax.swing.JTextField();
        txtmonth = new com.toedter.calendar.JMonthChooser();
        jLabel3 = new javax.swing.JLabel();
        btnreload2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnreload = new javax.swing.JButton();
        txtstatus = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        otherbill_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Bill Id", "Category", "Year", "Month", "Ammount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        otherbill_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otherbill_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(otherbill_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 860, 620));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Bill Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 303, -1));

        txtbillid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbillidActionPerformed(evt);
            }
        });
        getContentPane().add(txtbillid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 202, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bill Id");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 204, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 93, -1));

        txtcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light Bill", "Water Bill", "Rent Fee", "Other", " " }));
        txtcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoryActionPerformed(evt);
            }
        });
        getContentPane().add(txtcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 202, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Year");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 43, -1));

        txtyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtyearActionPerformed(evt);
            }
        });
        getContentPane().add(txtyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 202, -1));
        getContentPane().add(txtmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 194, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Month");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 68, -1));

        btnreload2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnreload2.setForeground(new java.awt.Color(0, 0, 153));
        btnreload2.setText("Exit");
        btnreload2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreload2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreload2MouseClicked(evt);
            }
        });
        btnreload2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreload2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnreload2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 150, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount(¥)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountActionPerformed(evt);
            }
        });
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 202, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Bill Id");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        btnreload.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnreload.setForeground(new java.awt.Color(0, 0, 153));
        btnreload.setText("Reload");
        btnreload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreloadActionPerformed(evt);
            }
        });
        getContentPane().add(btnreload, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 150, 40));

        txtstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paid", "Unpaid" }));
        getContentPane().add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 202, -1));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 150, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 138, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 204));
        jButton5.setText("Update");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 100, 45));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 204));
        jButton7.setText("Search");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 100, 45));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Add");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 100, 45));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("Delete");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 100, 45));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/popupicon/otherexpenses.png"))); // NOI18N
        jLabel6.setText("photo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbillidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbillidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbillidActionPerformed

    private void txtyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtyearActionPerformed

    private void txtcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoryActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//save button

        try {
            // 1. Get form values
            String billId = txtbillid.getText().trim();
            String category = txtcategory.getSelectedItem().toString();
            String year = txtyear.getText().trim();
            int month = txtmonth.getMonth() + 1; // Assuming this returns int (0-11) int month = txtmonth.getMonth()+1; 
            BigDecimal amount = new BigDecimal(txtamount.getText().trim());
            String status = txtstatus.getSelectedItem().toString();

            // Basic input validation
            if (billId.isEmpty() || year.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all required fields.");
                return;
            }

            // 2. Insert into 'otherbills' table
            String sql1 = "INSERT INTO otherbills (biiid, category, year, month, amount, status) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = db.myccon().prepareStatement(sql1);
            pst.setString(1, billId);
            pst.setString(2, category);
            pst.setString(3, year);
            pst.setInt(4, month);
            pst.setBigDecimal(5, amount);
            pst.setString(6, status);

            pst.executeUpdate(); // ✅ Execute insert

            // 3. Insert into 'otherbillreport' table
            String sql2 = "INSERT INTO otherbillreport (billid, status, amount) VALUES (?, ?, ?)";
            PreparedStatement sst = db.myccon().prepareStatement(sql2);
            sst.setString(1, billId);
            sst.setString(2, status);
            sst.setBigDecimal(3, amount);

            sst.executeUpdate(); // ✅ Execute second insert

            JOptionPane.showMessageDialog(this, "Bill saved successfully!");

            // 4. Clear form fields
            txtbillid.setText("");
            txtcategory.setSelectedIndex(0);
            txtyear.setText("");
            txtmonth.setMonth(0); // reset month picker
            txtamount.setText("");
            txtstatus.setSelectedIndex(0);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number entered. Please check the amount.");
        } catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Duplicate entry for Bill ID.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String billid = txtbillid.getText();  // Get bill ID from input field

        if (billid.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter or select a Bill ID to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete this record?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM otherbills WHERE biiid = ?";
                PreparedStatement ps = db.myccon().prepareStatement(sql);
                ps.setString(1, billid);

                int rows = ps.executeUpdate();

                if (rows > 0) {
                    JOptionPane.showMessageDialog(null, "Record deleted successfully.");

                    // Clear the fields if needed
                    txtbillid.setText("");
                    txtyear.setText("");
                    txtamount.setText("");
                    txtmonth.setMonth(1); // resets month
                    txtcategory.setSelectedIndex(0);
                    txtstatus.setSelectedIndex(0);

                } else {
                    JOptionPane.showMessageDialog(null, "No record found with this Bill ID.");
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error occurred: " + e.getMessage());
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {

            Statement s = db.myccon().createStatement();  //to creeate statement in search button

            ResultSet rs = s.executeQuery("SELECT * FROM otherbills WHERE biiid = '" + txtbillid.getText() + "'"); //Result set is a inbuild t java class

            if (rs.next()) {

                txtcategory.setSelectedItem(rs.getString("category"));
                txtyear.setText(rs.getString("year"));
                txtmonth.setMonth(rs.getInt("month"));
                txtamount.setText(rs.getString("amount"));
                txtstatus.setSelectedItem(rs.getString("status"));

            }

        } catch (SQLException e) {
            System.out.println(e);

        }        // TODO add your handling code here:


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

              String billid = txtbillid.getText();
String category = txtcategory.getSelectedItem().toString();
String year = txtyear.getText();
int month = txtmonth.getMonth() + 1;
double amount = Double.parseDouble(txtamount.getText());
String status = txtstatus.getSelectedItem().toString();

try {
    Statement s = db.myccon().createStatement();
    String sql = "UPDATE otherbills SET biiid = '" + billid
            + "', category = '" + category
            + "', year = '" + year
            + "', month = '" + month
            + "', amount = " + amount
            + ", status = '" + status
            + "' WHERE biiid = '" + billid + "'";

    int rowsAffected = s.executeUpdate(sql);
    if (rowsAffected > 0) {
        // Show popup message with info icon
        JOptionPane.showMessageDialog(null, "Updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No rows updated. Check if bill ID exists.", "Warning", JOptionPane.WARNING_MESSAGE);
    }

} catch (SQLException e) {
    // Show popup with error icon
    JOptionPane.showMessageDialog(null, "Update failed!\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace(); // for debugging
}


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreloadActionPerformed
        billtableload();
        // TODO add your handling code here:


    }//GEN-LAST:event_btnreloadActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        //Serach from id
        String billid = txtsearch.getText();

        try {
            DefaultTableModel dt = (DefaultTableModel) otherbill_table.getModel();
            dt.setRowCount(0);  // Clear existing rows before loading new ones

            Statement s = db.myccon().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM otherbills WHERE biiid = '" + billid + "'");

            while (rs.next()) {
                Vector v = new Vector();

                // Add each column value from the result set to the vector
                v.add(rs.getString("biiid"));
                v.add(rs.getString("category"));
                v.add(rs.getString("year"));
                v.add(rs.getString("month"));
                v.add(rs.getString("amount"));
                v.add(rs.getString("status"));

                // ✅ Add the vector as a row to the table model
                dt.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();  // Print error to the console
            JOptionPane.showMessageDialog(null, "Error loading data into table: " + e.getMessage());
        }


    }//GEN-LAST:event_txtsearchKeyPressed

    private void otherbill_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherbill_tableMouseClicked
        // TODO add your handling code here:
        
        int i = otherbill_table.getSelectedRow();

if (i != -1) {
    String billid = otherbill_table.getValueAt(i, 0).toString();
    String category = otherbill_table.getValueAt(i, 1).toString();
    String year = otherbill_table.getValueAt(i, 2).toString();
    String month = otherbill_table.getValueAt(i, 3).toString();
    String amount = otherbill_table.getValueAt(i, 4).toString();
    String status = otherbill_table.getValueAt(i, 5).toString(); // Fixed column index for status

    // Set values to input fields
    txtbillid.setText(billid);
    txtcategory.setSelectedItem(category);  // Assuming it's a JComboBox
    txtyear.setText(year);
    
    // Assuming txtmonth is a JMonthChooser (from com.toedter.calendar)
    txtmonth.setMonth(Integer.parseInt(month) - 1); // Months are 0-based in JMonthChooser

    txtamount.setText(amount);
    txtstatus.setSelectedItem(status);  // Assuming it's a JComboBox
}

    }//GEN-LAST:event_otherbill_tableMouseClicked

    private void btnreload2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreload2ActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btnreload2ActionPerformed

    private void btnreload2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreload2MouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btnreload2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Otherexpences1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Otherexpences1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Otherexpences1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Otherexpences1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Otherexpences1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreload;
    private javax.swing.JButton btnreload2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable otherbill_table;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtbillid;
    private javax.swing.JComboBox<String> txtcategory;
    private com.toedter.calendar.JMonthChooser txtmonth;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JComboBox<String> txtstatus;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
