/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autozencarmanagmentsystem;

import employee.Dashboard1;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author malsh
 */
public class Log extends javax.swing.JFrame {

    /**
     * Creates new form Log
     */
    
    private static Log instance = null; //singleton pattern hold only one intance

public static Log getInstance()  { //ensure the same log instance is resued
    if (instance == null) {
        instance = new Log(); //create onlt this instance
       
    }
    return instance;
}

   private Log() { //prevent creating new log objects only one can add
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnemployee = new javax.swing.JRadioButton();
        btnadmin = new javax.swing.JRadioButton();
        txtpassword = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnemployee.setBackground(new java.awt.Color(0, 0, 0));
        btnemployee.setForeground(new java.awt.Color(255, 255, 255));
        btnemployee.setText("employee");
        getContentPane().add(btnemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        btnadmin.setBackground(new java.awt.Color(0, 0, 0));
        btnadmin.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin.setText("admin");
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });
        getContentPane().add(btnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        txtpassword.setText("1234");
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 244, 31));

        txtusername.setText("admin");
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 244, 31));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setText("Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Welcome ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 37, 21));

        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("AutoZen Car Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/popupicon/Newlogin.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

       

       
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);   //0 used is the exit status code
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String username = txtusername.getText();
String password = new String(txtpassword.getPassword());

ButtonGroup roleGroup = new ButtonGroup(); // Create a new button group
roleGroup.add(btnadmin);                 // Add the Admin radio button
roleGroup.add(btnemployee);              // Add the Employee radio button


if (btnadmin.isSelected()) {
    // Admin login check
    if (username.equals("admin") && password.equals("1234")) {
        JOptionPane.showMessageDialog(this, "Admin Login Successful!");
        this.setVisible(false);
        Dashboard2 gamma = new Dashboard2(); // your admin dashboard
        gamma.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Invalid admin credentials!", "Login Failed", JOptionPane.ERROR_MESSAGE);
    }

} else if (btnemployee.isSelected()) {
    // Employee login check
    if (username.equals("employee") && password.equals("1234")) {
        JOptionPane.showMessageDialog(this, "Employee Login Successful!");
        this.setVisible(false);
        Dashboard1 gamma = new Dashboard1(); // or EmployeeDashboard if different
        gamma.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Invalid employee credentials!", "Login Failed", JOptionPane.ERROR_MESSAGE);
    }

} else {
    // No radio button selected
    JOptionPane.showMessageDialog(this, "Please select Admin or Employee before logging in!", "Login Failed", JOptionPane.WARNING_MESSAGE);
}


        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> //new gui theme in java

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Log.getInstance().setVisible(true); //always the same window come call for singleto

            }
        });
    } 
    
    /*new Log().setVisible(true);
new Log().setVisible(true);  can create objects like this*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnadmin;
    private javax.swing.JRadioButton btnemployee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
